### PR TITLE
Multipath plugin

### PR DESCRIPTION
**Pull request by cathay4t**
**Do not commit yet, please wait dm-devl accept the changes about C API of multipath.**

* Use [libdmmp.h][1] to extend these existing interfaces:
```
org.storaged.Storaged.Drive
        |
        |
        v
org.storaged.Storaged.Multipath

org.storaged.Storaged.Block  (/dev/dm-2 or /dev/sdb)
        ^
        |
        v
org.storaged.Storaged.Multipath

org.storaged.Storaged.Block (/dev/sdb)
        ^
        |
        v
org.storaged.Storaged.Multipath.PathGroup.Path
```
* How to install:
```
./autogen.sh  \
    --libdir=/usr/lib64 --prefix=/usr  --sysconfdir /etc
    --disable-lvm2 --disable-dummy --disable-iscsi \
    --enable-multipath
make -j5
sudo make install
sudo /usr/libexec/storaged/storaged --force-load-modules
```
[1]: https://www.redhat.com/archives/dm-devel/2016-February/msg00093.html

### CODE REVIEW

**Comment by phatina** [comment]
Hi Gris, can you give me some heads up about the Multipath API? Can we merge this or do I have to wait a bit longer? Thanks

**Comment by cathay4t** [comment]
@phatina Hi Peter, I am still waiting [dm-devel][1] to accept my V2 patch there. Once they commited, we could review this PR.

If we need this feature badly, we could follow the plan B:

 * Move the libdmmp to storaged multipath plugin instead as libdmmp is standalone[2].

 * Once dm-devel accepted libdmmp, we purge it out from storaged and use upstream one.

[1]: https://www.redhat.com/archives/dm-devel/2016-February/msg00093.html
[2]: It just use multipathd IPC socket.

**Comment by phatina** [comment]
OK, Gris. I was curious, because Todd told me, that your patches were dismissed, but now I know, that you are still in the game. Let's wait then for the review...

**Comment by cathay4t** [comment]
Yeah. The V1 patch was dismissed.

**Pull request closed without merging**
