### PR TITLE
Packaging: Add 'rpm' make target; build the spec file by autoconf

### PR DESCRIPTION
**Pull request by tsmetana**
This should make the automated testing on RPM based systems a bit easier. Those who are not interested in RPM packaging should not encounter any problems. It should also build an rpm package outside of the git tree (like from the release tarball).

### CODE REVIEW

**Comment by phatina** [comment]
@tsmetana I am not sure about this - take a look at our internat "CI" - this templated storaged.spec.in may cause troubles when installing Storaged dependencies.

**Comment by tsmetana** [comment]
That's it. I'm not sure whether it's more valuable to be able to use 'dnf builddep' right away or have an properly versioned rpm built from the git tree... I'll try to figure out how to have both. It's not that important anyway.

**Comment by phatina** [comment]
For this purpose, it may be worth redesigning the dependencies installation (dnf-builddep was the easiest one)..

**Comment by tsmetana** [comment]
Let's abandon this for the moment...

**Pull request closed without merging**
