### PR TITLE
Patch V3: New module -- lsm: Use LibStorageMgmt for RAID information.

### PR DESCRIPTION
**Pull request by cathay4t**
New lsm module using LibStorageMgmt API.

    * Using LibStorageMgmt API to query external(DAS and SAN) storage RAID
      information and expose it via "org.storaged.Storaged.Drive.LSM" interface.
      The manpage included "storaged_lsm.conf(5)" include details.

    * Workflow:
        * Build in LibStorageMgmt URI:
            * sim://
                Using simulator of LibStorageMgmt, for develop only.
                Disabled by default.
            * hpsa://
                For HP SmartArray. Enabled by default. Require 'hpssacli' binary
                tool installed. The 'libstoragemgmt-hpsa-plugin' is also required.
                Check "storaged-lsm.conf(5)" manpage for detail.
        * Extra LibStorageMgmt URI can be defined in storaged-lsm.conf like:
            extra_uris = ["ontap+ssl://root@ontap.a.ip", "ontap://root@nb.ip"]
            extra_passwords = ["password_string_1", "password_string_2"]
        * Matching storaged Linux drive using udev 'ID_WWN_WITH_EXTENSION'
          against LibStorageMgmt volume VPD83 value.
        * Use LibStorageMgmt lsm_volume_raid_info(), lsm_pools(), lsm_volumes()
          methods to query disk drive RAID information.
        * Use glib main loop to refresh RAID status in given interval.

    * Add configure script option '--enable-lsm'.
    * Add DBUS API document and manpage "storaged-lsm.conf(5)".
    * Requires:
        libstoragemgmt-devel > 1.2
            # The lsm_volume_raid_info() is introduced by 1.2 release.
        libconfig-devel > 1.3.2
            # The version 1.3.2 is the shipped by RHEL6. I was referring to
            # document shipped by RHEL 6.
            # Used to read/parse storage_lsm.conf.

    * Tested hardwares(RHEL 7.1):
        * HP SmartArray
        * NetApp ONTAP

    * Using GNU Code style, enforced this command:
        indent --gnu-style --no-tabs --line-length79

The developer notes(including how to setup a develop/test environment) is in
`README_DEV_lsm.txt`

The test detail is in `TEST_NOTE_lsm.txt`.

### CODE REVIEW

**Comment by phatina** [comment]
Please, update the coding style (GNU, see other sources). Thank you :)

**Comment by cathay4t** [comment]
Thanks for the review.
Will fix them soon.

**Comment by cathay4t** [comment]
V2 patch sent.

Changes:
1. GNU code style.
2. Changed C name space to "Storaged" like other modules(except dummy).
3. Included man page `storaged_lsm.conf(5)` and auto generated dbus interface document.

**Comment by tasleson** [comment]
When trying to build I'm failing for:
make[5]: Entering directory '/home/tasleson/projects/storaged/modules/lsm/data'
make[5]: *** No rule to make target 'storaged_lsm.conf', needed by 'all-am'.  Stop.

Missing file?

**Comment by tasleson** [comment]
@cathay4t I've only partially reviewed lsm_data.[h|c],  will look at some more next week.  It would be helpful if you explained the overall design, especially with what you are trying to achieve with the threading to ensure correct usage.

**Comment by cathay4t** [comment]
V3 patch uploaded, changes:

1. Added two documents: `README_DEV_lsm.txt` and `TEST_NOTE_lsm.txt`
1. Use glib main loop event instead of thread for data refreshing.
1. Include two extra patches to storaged code:
  1. Fix memory leak in storaged_log().
  1. Fix a warning message.
1. Fixed memory leak.
1. Rewrite the `lsm_data.c` file to simplify the workflow.
1. Use glib memory management, like:
   * `GDestroyNotify` of `g_hash_table_new_full ()`
   * `GDestroyNotify` of `g_ptr_array_new_full ()`
   * `g_object_add_weak_pointer ()`
   * `g_object_unref` in `storaged_linux_drive_lsm_finalize()`
1. Removed the signal for property change. User should use 
    `org.freedesktop.DBus.Properties.PropertiesChanged` instead.
1. Removed the `org.storaged.Storaged.Drive.LSM.IsManged`.
    The existance of `org.storaged.Storaged.Drive.LSM` indicate that.

**Comment by cathay4t** [comment]
@tasleson Thanks for the detail review. 
I have included extra dev notes in `README_DEV_lsm.txt` file.

**Comment by cathay4t** [comment]
Tested on HP SmartArray and ONTAP simulator.

**Comment by cathay4t** [comment]
Rebased to current master.

**Pull request merged**
